language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2.2
before_script:
  - 'cp config/application.travis.yml config/application.yml'
  - "psql -c 'create database x0y0_test;' -U postgres"
  - 'bundle exec rake db:migrate'
