common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'store' %>
  password: <%= ENV['TRAVIS'] ? '' : 'store' %>

development:
  database: store_development
  <<: *common

test:
  database: store_test
  <<: *common

production:
  database: store_production
  <<: *common

sandbox:
  database: store_production
  <<: *common
