default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'store' %>
  password: <%= ENV['TRAVIS'] ? '' : 'store' %>

development:
  <<: *default
  database: store_development

test:
  <<: *default
  database: store_test

production:
  <<: *default
  database: store_production

sandbox:
  <<: *default
  database: store_production
